server {
    listen 80;
    server_name voidwhispr.org www.voidwhispr.org;
    root /var/www/asmr;
    index index.html;
}

server {
    listen 80;
    server_name mythic-counseling.org www.mythic-counseling.org;
    root /var/www/counseling;
    index index.html;
}

server {
    listen 80;
    server_name astral-power.org www.astral-power.org;
    root /var/www/energy;
    index index.html;
}

server {
    listen 80;
    server_name puggers-insurance.org www.puggers-insurance.org;
    root /var/www/insurance;
    index index.html;
}

server {
    listen 80;
    server_name azerothweather.org www.azerothweather.org;
    root /var/www/meteo;
    index index.html;
}

server {
    listen 80;
    server_name learn-thalassian.org www.learn-thalassian.org;
    root /var/www/thalassian;
    index index.html;
}
